baseURL = "https://haodq4.github.io/"
languageCode = "en-us"
title = "Coding & Life"
theme = "PaperMod"

[pagination]
  pagerSize = 10

googleAnalytics = "G-TGHCE00QZV"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
canonifyURLs = true

[params]
  env = "production"
  description = "A personal blog where I share programming knowledge and life experiences"
  author = "Duong Quoc Hao"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowShareButtons = true
  defaultTheme = "auto"

  [params.profileMode]
    enabled = true
    title = "Hi, I'm Duong Quoc Hao 👋"
    subtitle = """I'm a software developer passionate about technology.

Welcome to my personal blog — a place where I share programming knowledge and life experiences.

I hope you'll find something helpful and inspiring here!
"""
    imageUrl = "images/avatar.png"
    imageTitle = "Hao's avatar"
    imageWidth = 120
    imageHeight = 120

    buttons = [
      { name = "Posts", url = "/posts/" },
      { name = "About", url = "/about/" }
    ]

  [params.assets]
    disableFingerprinting = true

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/haodq4"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[markup]
  [markup.highlight]
    noClasses = false

  [markup.goldmark.renderer]
    unsafe = true
